@ dockerfiles

diff --git a/ayubuntu/Makefile b/ayubuntu/Makefile
--- a/ayubuntu/Makefile
+++ b/ayubuntu/Makefile
@@ -8,6 +8,7 @@ help:
 	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z0-9_-]+:.*?## / {printf "\033[36m%-16s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)
 	@echo
 	@echo 'To build images, choose one of the VERSION:'
+	@echo '  - 24.04'
 	@echo '  - 26.04'
 	@echo
 	@echo 'Example:'
@@ -15,17 +16,64 @@ help:
 	@echo '  - VERSION=26.04 make build-aarch64'
 
 define check_vars
-	@ if [ "$(VERSION)" = "" ]; then echo " <- Env variable VERSION not set"; exit 1; fi
+	@ if [ "$(VERSION)" = "" ]; then \
+		echo "Error: Env variable VERSION not set"; \
+		echo ""; \
+		exit 1; \
+	fi
+endef
+
+define check_modern_versions
+	@ if [ "$(VERSION)" != "24.04" ] && [ "$(VERSION)" != "26.04" ]; then \
+		echo "Error: Unsupported version $(VERSION)."; \
+		echo "  '$(1)' accepts: 26.04, 24.04"; \
+		echo ""; \
+		echo "  For $(VERSION), use:"; \
+		echo "    make build-classic"; \
+		echo "    make build-classic-aarch64"; \
+		echo ""; \
+		exit 1; \
+	fi
 endef
 
 .PHONY: help build build-aarch64
 
 build: ## Build image in amd64
 	@$(call check_vars)
+	@$(call check_modern_versions,make build)
 	@echo " - version: $(VERSION)"
-	@docker buildx build --platform linux/amd64 --progress=plain --file ./docker/ubuntu-$(VERSION).dockerfile -t $(TAG)-amd64 ./docker
+	@docker buildx build --platform linux/amd64 \
+		--build-arg UBUNTU_VERSION=$(VERSION) \
+		--build-arg TARGET_ARCH=amd64 \
+		--file ./docker/ubuntu.dockerfile \
+		-t $(TAG)-amd64 ./docker
 
 build-aarch64: ## Build image in aarch64
 	@$(call check_vars)
+	@$(call check_modern_versions,make build-aarch64)
 	@echo " - version: $(VERSION)"
-	@docker buildx build --platform linux/arm64 --progress=plain --file ./docker/ubuntu-$(VERSION)-aarch64.dockerfile -t $(TAG)-aarch64 ./docker
+	@docker buildx build --platform linux/arm64 \
+		--build-arg UBUNTU_VERSION=$(VERSION) \
+		--build-arg TARGET_ARCH=aarch64 \
+		--file ./docker/ubuntu.dockerfile \
+		-t $(TAG)-aarch64 ./docker
+
+build-classic:
+	@$(call check_vars)
+	@echo " - version: $(VERSION)"
+	@docker buildx build --platform linux/amd64 \
+		--build-arg UBUNTU_VERSION=$(VERSION) \
+		--build-arg TARGET_ARCH=amd64 \
+		--build-arg DISABLE_DEB822=1 \
+		--file ./docker/ubuntu.dockerfile \
+		-t $(TAG)-classic-amd64 ./docker
+
+build-classic-aarch64:
+	@$(call check_vars)
+	@echo " - version: $(VERSION)"
+	@docker buildx build --platform linux/arm64 \
+		--build-arg UBUNTU_VERSION=$(VERSION) \
+		--build-arg TARGET_ARCH=aarch64 \
+		--build-arg DISABLE_DEB822=1 \
+		--file ./docker/ubuntu.dockerfile \
+		-t $(TAG)-classic-aarch64 ./docker
